# Generated by Django 4.2.6 on 2023-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('task', models.TextField(verbose_name='Комментарий')),
                ('phone_num', models.TextField(verbose_name='Номер телефона')),
                ('mail', models.TextField(verbose_name='почта')),
                ('name_car', models.TextField(verbose_name='Название машины')),
            ],
        ),
    ]
