# Generated by Django 4.2.6 on 2023-10-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_mail_alter_task_name_car_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Арендовал', 'verbose_name_plural': 'Арендовали'},
        ),
    ]
